
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AL AR BY COLON COMMA DENSE L R SEQUENCE SPARSE SYM\n    rule    : head seq\n    \n    head    : SYM COLON SPARSE SEQUENCE\n            | SYM COLON SPARSE SEQUENCE commonkeys\n            | SYM COLON DENSE SEQUENCE\n            | SYM COLON DENSE SEQUENCE commonkeys\n    \n    commonkeys  : BY farr\n    \n    farr    : farr COMMA SYM\n            | SYM\n    \n    seq : seq event\n        | event\n    \n    event   : AL SYM AR BY constraint\n            | AL SYM AR\n    \n    constraint  : constraint COMMA L farr R COLON SYM\n                | L farr R COLON SYM\n    '
    
_lr_action_items = {'SYM':([0,6,17,20,25,26,30,33,],[3,9,22,22,28,22,32,34,]),'$end':([1,4,5,8,12,19,32,34,],[0,-1,-10,-9,-12,-11,-14,-13,]),'AL':([2,4,5,8,12,13,14,16,18,19,21,22,28,32,34,],[6,6,-10,-9,-12,-2,-4,-3,-5,-11,-6,-8,-7,-14,-13,]),'COLON':([3,27,31,],[7,30,33,]),'SPARSE':([7,],[10,]),'DENSE':([7,],[11,]),'AR':([9,],[12,]),'SEQUENCE':([10,11,],[13,14,]),'BY':([12,13,14,],[15,17,17,]),'L':([15,23,],[20,26,]),'COMMA':([19,21,22,24,28,29,32,34,],[23,25,-8,25,-7,25,-14,-13,]),'R':([22,24,28,29,],[-8,27,-7,31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rule':([0,],[1,]),'head':([0,],[2,]),'seq':([2,],[4,]),'event':([2,4,],[5,8,]),'commonkeys':([13,14,],[16,18,]),'constraint':([15,],[19,]),'farr':([17,20,26,],[21,24,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule","S'",1,None,None,None),
  ('rule -> head seq','rule',2,'p_rule','xeql_yacc.py',44),
  ('head -> SYM COLON SPARSE SEQUENCE','head',4,'p_head','xeql_yacc.py',52),
  ('head -> SYM COLON SPARSE SEQUENCE commonkeys','head',5,'p_head','xeql_yacc.py',53),
  ('head -> SYM COLON DENSE SEQUENCE','head',4,'p_head','xeql_yacc.py',54),
  ('head -> SYM COLON DENSE SEQUENCE commonkeys','head',5,'p_head','xeql_yacc.py',55),
  ('commonkeys -> BY farr','commonkeys',2,'p_commonkeys','xeql_yacc.py',65),
  ('farr -> farr COMMA SYM','farr',3,'p_farr','xeql_yacc.py',72),
  ('farr -> SYM','farr',1,'p_farr','xeql_yacc.py',73),
  ('seq -> seq event','seq',2,'p_seq','xeql_yacc.py',83),
  ('seq -> event','seq',1,'p_seq','xeql_yacc.py',84),
  ('event -> AL SYM AR BY constraint','event',5,'p_event','xeql_yacc.py',94),
  ('event -> AL SYM AR','event',3,'p_event','xeql_yacc.py',95),
  ('constraint -> constraint COMMA L farr R COLON SYM','constraint',7,'p_constraint','xeql_yacc.py',105),
  ('constraint -> L farr R COLON SYM','constraint',5,'p_constraint','xeql_yacc.py',106),
]
